### ISSUE TITLE
Think about how to test simplicity programs

### ISSUE THREAD

**Issue by sanket1729** [BlockstreamResearch/rust-simplicity#15]
Some simplicity programs take too long to run and execute. As the project development increases, there would be more programs that would end up taking 15mins+ on local machine. Ideally, we want to test those programs against every PR but that would result in a very slow CI. 

As of now, all these expensive tests are marked as ignored.
I suggest having a cron scheduled job at github CI to execute these every midnight.

**Comment by apoelstra** [comment]
I think we could just feature-gate these "big" tests and try to get complete coverage using small and simple programs.

**Comment by apoelstra** [comment]
I'm going to close this. The original issue ("standard" test programs taking 15+ minutes to execute) is long gone since all our normal test programs use jets. We also have consensus limits now which will prevent any such massive programs from running on-chain, so the value of testing them is limited. Finally, as far as long-term testing goes, we are driving toward being able to run fuzztests between the C and Rust implementations, and we don't need an issue to track that. Or if we do, we don't need this issue.
